Added permissions to all files

diff --git a/0x08-networking_basics_2/0-change_your_home_IP b/0x08-networking_basics_2/0-change_your_home_IP
--- a/0x08-networking_basics_2/0-change_your_home_IP
+++ b/0x08-networking_basics_2/0-change_your_home_IP
@@ -1,6 +1,21 @@
 #!/usr/bin/env bash
 #Steps to change the localhosts and the facebook.com IP address
-cp /etc/hosts ~/changehosts
-sed -i 's/127.0.0.1/127.0.0.2/g' ~/changehosts
-echo "8.8.8.8 facebook.com" >> ~/changehosts
-cp -f ~/changehosts /etc/hosts
+
+if (( ${UID:-$(id -u)} ))
+then
+  echo 'Must be run as root'
+  exit 1
+fi
+
+if ! tempfile="$(mktemp)"
+then
+  echo 'Unable to create temporary file'
+  exit 1
+fi
+
+{ printf '%s\t%s\n' 127.0.0.2 localhost
+  printf '%s\t%s\n' 8.8.8.8   facebook.com
+  cat /etc/hosts
+} > "${tempfile}"
+
+cat -- "${tempfile}" > /etc/hosts
